In [212]:
import numpy as np

In [213]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [214]:
# 1
len(a[a < 0])

4

In [215]:
# joey's way: (a<0).sum()

In [216]:
# 2
len(a[a > 0])

5

In [217]:
# 3
len(a[(a > 0) & (a % 2 == 0)])

3

In [218]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [219]:
a_even = np.array([a + 3])

In [220]:
# 4
len(a_even[a_even > 0])

10

In [221]:
a.mean()

3.0

In [222]:
a_mean = a.mean()

In [223]:
a.std()

8.06225774829855

In [224]:
a_std = a.std()

In [225]:
np.square(a)

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [226]:
np.square(a).mean()

74.0

In [50]:
# 5
np.square(a).std()

144.0243035046516

In [230]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [231]:
# 6
a_center = a - a_mean

In [232]:
a_center

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [233]:
a_center.mean() # verification that you are centered!

0.0

In [234]:
# 7
a_center / a_std

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [237]:
# 7
(a - a_mean) / a_std

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [62]:
a_zscore = a_center / a_std

In [63]:
a_zscore

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

### Send More Numpy

In [65]:
# import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

# Exercise 9 - print out the shape of the array b.

# Exercise 10 - transpose the array b.

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2

## Setup 1

In [83]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [94]:
# 1
sum_of_a = 0
for num in a:
    sum_of_a += num
sum_of_a

55

In [90]:
# 2
min_of_a = min(a)
min_of_a

1

In [91]:
# 3
max_of_a = max(a)
max_of_a

10

In [93]:
# 4
mean_of_a = sum_of_a / len(a)
mean_of_a

8.0

In [100]:
# 5 ????
product_of_a = 0
for num in a:
    product_of_a += (num*num)
product_of_a

385

In [102]:
# 6 ???
squares_of_a = []
for n in a:
    new_a = n**2
    squares_of_a.append(new_a)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [106]:
# 7
odds_in_a = []
evens_in_a = []
for n in a:
    if n % 2 == 1:
        odds_in_a.append(n)
    else:
        evens_in_a.append(n)
odds_in_a

[1, 3, 5, 7, 9]

In [107]:
# 8
evens_in_a

[2, 4, 6, 8, 10]

## Setup 2

In [108]:
b

[[3, 4, 5], [6, 7, 8]]

In [115]:
type(b)

numpy.ndarray

In [114]:
b = np.array([3, 4, 5, 6, 7, 8])

In [126]:
# 1
sum_of_b = sum(b)
sum_of_b

33

In [127]:
# 2
min_of_b = min(b)
min_of_b

3

In [128]:
# 3
max_of_b = max(b)
max_of_b

8

In [129]:
# 4
mean_of_b = b.mean()
mean_of_b

5.5

In [132]:
# 5
product_of_b = b.prod()
product_of_b

20160

In [136]:
# 6
squares_of_b = np.square(b)
squares_of_b

array([ 9, 16, 25, 36, 49, 64])

In [137]:
# 7
odds_in_b = b[b % 2 == 1]
odds_in_b

array([3, 5, 7])

In [138]:
# 8
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [148]:
# 9
b.shape# 6 columns 0 rows

(6,)

In [150]:
# 10
b.transpose() #didn't do anything because it is an array - not a matrix

array([3, 4, 5, 6, 7, 8])

In [153]:
# 11
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [154]:
# 12
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [161]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
type(c)

numpy.ndarray

In [160]:
c = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
# 1
min(c)

1

In [164]:

max(c)

9

In [165]:

sum(c)

45

In [167]:

np.prod(c)

362880

In [172]:
# 2
c.std()

2.581988897471611

In [173]:
# 3
c.var()

6.666666666666667

In [171]:
# 4
print(c.shape)

(9,)


In [168]:
# 5
print(c.transpose())

[1 2 3 4 5 6 7 8 9]


In [174]:
# 6
np.dot(c,c)

285

In [185]:
# 7 ???
ct = c*(c.transpose())
ct
sum_ct = np.sum(ct)
sum_ct

285

In [184]:
# 8
prod_ct = np.prod(ct)
prod_ct

131681894400

## 4

In [186]:
d

[[90, 30, 45, 0, 120, 180],
 [45, -90, -30, 270, 90, 0],
 [60, 45, -45, 90, -45, 180]]

In [189]:
type(d)

numpy.ndarray

In [188]:
d = np.array([90, 30, 45, 0, 120, 180, 45, -90, -30, 270, 90, 0, 60, 45, -45, 90, -45, 180])
d

array([ 90,  30,  45,   0, 120, 180,  45, -90, -30, 270,  90,   0,  60,
        45, -45,  90, -45, 180])

In [192]:
# 1
np.sin(d)

array([ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
       -0.80115264,  0.85090352, -0.89399666,  0.98803162, -0.17604595,
        0.89399666,  0.        , -0.30481062,  0.85090352, -0.85090352,
        0.89399666, -0.85090352, -0.80115264])

In [194]:
# 2
np.cos(d)

array([-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
       -0.59846007,  0.52532199, -0.44807362,  0.15425145,  0.98438195,
       -0.44807362,  1.        , -0.95241298,  0.52532199,  0.52532199,
       -0.44807362,  0.52532199, -0.59846007])

In [195]:
# 3
np.tan(d)

array([-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
        1.33869021,  1.61977519,  1.99520041,  6.4053312 , -0.17883906,
       -1.99520041,  0.        ,  0.32004039,  1.61977519, -1.61977519,
       -1.99520041, -1.61977519,  1.33869021])

In [196]:
# 4
d[d < 0]

array([-90, -30, -45, -45])

In [197]:
# 5
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [200]:
# 6
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [202]:
# 7
len(np.unique(d))

11

In [204]:
# 8
d.shape

(18,)

In [205]:
# 9
print(d.transpose())

[ 90  30  45   0 120 180  45 -90 -30 270  90   0  60  45 -45  90 -45 180]


In [206]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])